# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "parse_cargo_toml"
edition = "2021"
version = "0.0.1"

[package.metadata]
update_date = "2025-12-31"

[dependencies]
chrono = "0.4"
semver = "1.0"
toml = "0.9"
